[package]
name = "enter32"
version = "0.1.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]

[dependencies]
gilrs = "^0.6"
rpi-led-matrix = { git = "https://github.com/sphinxc0re/rust-rpi-rgb-led-matrix.git" }
