[package]
name = "enter32"
version = "0.1.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
build = "build.rs"

[dependencies]
gilrs = "^0.6"
rpi-led-matrix = "^0.1"

[build-dependencies]
bindgen = "0.36.0"
